name: latest

on:
  release:
    types: [released]

jobs:
  update-latest:
    environment: release
    strategy:
      matrix:
        runner:
          - linux
          - ubuntu-22.04-ppc64le
    runs-on: ${{ matrix.runner }}
    steps:
      - run: |
          echo ${{ vars.DOCKER_USER }}
          echo ${{ env.DOCKER_USER }}
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Tag images as latest
        env:
          PUSH: "1"
        shell: bash
        run: |
          export "VERSION=${GITHUB_REF_NAME#v}"
          ./scripts/tag_latest.sh
